import { beforeEach, expect, test } from '@jest/globals';
declare const jest: typeof import('@jest/globals').jest;
jest.mock('server-only',()=>({}),{virtual:true});
jest.mock('@/lib/auth/session',()=>({getViewer:jest.fn()}));
jest.mock('@/lib/supabase/server',()=>({createSupabaseServerClient:jest.fn()}));
jest.mock('@/lib/activity',()=>({recordActivity:jest.fn(async()=>true)}));
import { GET,POST } from '@/app/api/logs/route';
import { getViewer } from '@/lib/auth/session';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { recordActivity } from '@/lib/activity';
const uid='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const result={data:[],count:0,error:null};
const query={select:jest.fn(),lte:jest.fn(),order:jest.fn(),eq:jest.fn(),ilike:jest.fn(),range:jest.fn(async(from:number,to:number)=>{void from;void to;return result;})};
const rpc=jest.fn(async(name:string)=>{void name;return {data:[{id:uid,name:'Owner',email:'owner@example.test'}],error:null};});
beforeEach(()=>{jest.clearAllMocks();jest.mocked(getViewer).mockResolvedValue({id:uid,fullName:'Owner',email:'owner@example.test',role:'customer'});for(const name of ['select','lte','order','eq','ilike'] as const)query[name].mockReturnValue(query);jest.mocked(createSupabaseServerClient).mockResolvedValue({from:()=>query,rpc} as unknown as Awaited<ReturnType<typeof createSupabaseServerClient>>);jest.mocked(recordActivity).mockResolvedValue(true);});
const post=(value:unknown)=>new Request('http://localhost/api/logs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
test('anonymous reads and UI writes are denied before accessing logs',async()=>{jest.mocked(getViewer).mockResolvedValue(null);expect((await GET(new Request('http://localhost/api/logs'))).status).toBe(401);expect((await POST(post({type:'page.view',path:'/logs'}))).status).toBe(401);expect(createSupabaseServerClient).not.toHaveBeenCalled();expect(recordActivity).not.toHaveBeenCalled();});
test('customer cannot select another user or obtain the user directory',async()=>{expect((await GET(new Request('http://localhost/api/logs?userId='+other))).status).toBe(403);expect(createSupabaseServerClient).not.toHaveBeenCalled();const response=await GET(new Request('http://localhost/api/logs'));expect(response.status).toBe(200);expect(query.eq).toHaveBeenCalledWith('actor_id',uid);expect(rpc).not.toHaveBeenCalled();expect((await response.json()).users).toEqual([]);});
test('type search only targets interaction_type and treats wildcard characters literally',async()=>{const response=await GET(new Request('http://localhost/api/logs?page=2&type=transfer%25_'));expect(response.status).toBe(200);expect(query.ilike).toHaveBeenCalledWith('interaction_type','%transfer\\%\\_%');expect(query.range).toHaveBeenCalledWith(25,49);expect(response.headers.get('cache-control')).toBe('private, no-store');});
test('admin can filter users and receives directory options',async()=>{jest.mocked(getViewer).mockResolvedValue({id:uid,fullName:'Admin',email:'admin@example.test',role:'admin'});const response=await GET(new Request('http://localhost/api/logs?userId='+other));expect(query.eq).toHaveBeenCalledWith('actor_id',other);expect(rpc).toHaveBeenCalledWith('activity_filter_users');expect((await response.json()).users).toHaveLength(1);});
test('client cannot spoof actor identities or trusted login/transfer events',async()=>{expect((await POST(post({type:'login',path:'/logs'}))).status).toBe(400);expect((await POST(post({type:'ui.click',path:'/logs',actorId:other}))).status).toBe(400);expect(recordActivity).not.toHaveBeenCalled();expect((await POST(post({type:'ui.click',path:'/logs',label:'Next'}))).status).toBe(200);expect(recordActivity).toHaveBeenCalledWith(uid,'ui.click',expect.objectContaining({source:'browser'}));});
test('invalid pagination and cross-site UI submissions fail safely',async()=>{expect((await GET(new Request('http://localhost/api/logs?page=0'))).status).toBe(400);const request=new Request('http://localhost/api/logs',{method:'POST',headers:{Origin:'https://attacker.example','Content-Type':'application/json'},body:JSON.stringify({type:'page.view',path:'/logs'})});expect((await POST(request)).status).toBe(403);});
test('a logging outage is reported by the interaction endpoint',async()=>{jest.mocked(recordActivity).mockResolvedValue(false);expect((await POST(post({type:'page.view',path:'/logs'}))).status).toBe(503);});
